/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Api Root
         * @description 返回API信息
         *
         *     Returns:
         *         API基本信息
         */
        get: operations["api_root_api_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Session Info */
        get: operations["session_info_api_admin_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_admin_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete User */
        delete: operations["delete_user_api_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/auth/guest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guest Login */
        post: operations["guest_login_api_auth_guest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Session */
        get: operations["auth_session_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description 获取前端配置信息（包括 Google Maps API Key）
         *
         *     Returns:
         *         配置信息
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Conversations
         * @description 获取用户的所有对话列表
         *
         *     Args:
         *         user_id: 用户ID
         *
         *     Returns:
         *         对话摘要列表
         */
        get: operations["get_all_conversations_api_conversations__user_id__get"];
        put?: never;
        /**
         * Create Conversation
         * @description 创建新对话
         *
         *     Args:
         *         user_id: 用户ID
         *         request: 创建对话请求
         *
         *     Returns:
         *         创建的对话数据
         */
        post: operations["create_conversation_api_conversations__user_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description 获取单个对话的完整信息（包含所有消息）
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *
         *     Returns:
         *         完整的对话数据
         */
        get: operations["get_conversation_api_conversations__user_id___conversation_id__get"];
        /**
         * Update Conversation
         * @description 更新对话信息（如标题、模型等）
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *         request: 更新请求
         *
         *     Returns:
         *         更新后的对话数据
         */
        put: operations["update_conversation_api_conversations__user_id___conversation_id__put"];
        post?: never;
        /**
         * Delete Conversation
         * @description 删除对话
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *
         *     Returns:
         *         成功状态
         */
        delete: operations["delete_conversation_api_conversations__user_id___conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}/{conversation_id}/active-branch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Active Branch
         * @description Switch the active visible branch for a conversation.
         */
        put: operations["set_active_branch_api_conversations__user_id___conversation_id__active_branch_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Message
         * @description 向对话添加消息
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *         request: 添加消息请求
         *
         *     Returns:
         *         成功状态
         */
        post: operations["add_message_api_conversations__user_id___conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{user_id}/{conversation_id}/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation Preferences
         * @description 获取对话的偏好设置（优先从内存缓存获取）
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *
         *     Returns:
         *         偏好设置字典
         */
        get: operations["get_conversation_preferences_api_conversations__user_id___conversation_id__preferences_get"];
        /**
         * Update Conversation Preferences
         * @description 更新对话的偏好设置（同时更新内存缓存和持久化层）
         *
         *     Args:
         *         user_id: 用户ID
         *         conversation_id: 对话ID
         *         preferences_data: 偏好设置字典
         *
         *     Returns:
         *         更新后的偏好设置（从内存缓存返回）
         */
        put: operations["update_conversation_preferences_api_conversations__user_id___conversation_id__preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/llm-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Debug Llm Connection
         * @description Diagnose LLM connectivity from inside the running backend process.
         *
         *     Admin-only: it discloses LLM transport config and issues a live probe request,
         *     so it must not be reachable unauthenticated. The response is still redacted and
         *     does not expose API keys.
         */
        get: operations["debug_llm_connection_api_debug_llm_connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/domains/{domain}/preference-form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Domain Preference Form
         * @description Generate the (server-driven) preference form for a domain at request time.
         *     The frontend renders it generically; adding a domain's form is a data change.
         */
        get: operations["get_domain_preference_form_api_domains__domain__preference_form_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_api_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feedback/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Feedback Options */
        get: operations["feedback_options_api_feedback_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process User Request
         * @description 处理用户请求的统一接口
         *     融合了 LLM 意图识别、偏好提取、确认流程
         *
         *     这个接口会自动处理：
         *     - 使用 LLM 进行意图识别和生成回复
         *     - 如果是推荐餐厅请求：触发推荐流程
         *     - 如果是普通对话：返回 LLM 的回复
         *
         *     Args:
         *         query_data: {"query": "用户查询", "user_id": "用户ID（可选）", "conversation_history": "对话历史（可选）"}
         *
         *     Returns:
         *         根据处理结果返回不同的响应：
         *         - 如果是 LLM 回复：返回 llm_reply 字段
         *         - 如果是确认请求：返回确认请求对象
         *         - 如果是任务创建：返回任务ID
         *         - 如果是修改请求：返回修改提示
         */
        post: operations["process_user_request_api_process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description 获取任务状态
         *     前端通过轮询此接口获取任务进度和最终结果（SSE 不可用时的回退路径）
         *
         *     Args:
         *         task_id: 任务ID
         *         user_id: 用户ID（可选，提供后更精确查找）
         *         conversation_id: 会话ID（可选，提供后更精确查找）
         *
         *     Returns:
         *         任务状态信息，包括：
         *         - status: "processing" | "completed" | "error" | "cancelled"
         *         - progress: 0-100的进度值
         *         - message: 当前状态消息
         *         - result: 推荐结果（任务完成时）
         *         - error: 错误信息（任务失败时）
         */
        get: operations["get_task_status_api_status__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status/{task_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Task Status
         * @description Stream task progress as Server-Sent Events.
         *
         *     Replaces client-side 1s polling: the browser opens a single EventSource and
         *     the server pushes a status frame whenever the task projection changes, ending
         *     on completion/error. Reads the same projection the polling endpoint serves
         *     (no graph changes), so /api/status remains a working fallback when SSE can't
         *     get through (proxies, missing EventSource).
         */
        get: operations["stream_task_status_api_status__task_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Result
         * @description Resolve the durable recommendation persisted for a Task ID.
         *
         *     Reads from recommendation_results (the canonical, queryable source of truth),
         *     scoped to the owning user/conversation — used by the conversation side card and
         *     the /Debug testing arena to fetch a result by Task ID without re-deriving it
         *     from conversation messages.
         */
        get: operations["get_task_result_api_tasks__task_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/update-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Preferences Endpoint
         * @description 更新用户偏好设置
         *
         *     Args:
         *         preferences_data: 包含用户偏好的字典，格式：
         *         {
         *             "user_id": "用户ID（可选，默认'default'）",
         *             "restaurantTypes": ["casual", "fine-dining"],
         *             "flavorProfiles": ["spicy", "savory"],
         *             "diningPurpose": "friends",
         *             "budgetRange": {"min": 20, "max": 60, "currency": "SGD", "per": "person"},
         *             "location": "Chinatown"
         *         }
         *
         *     Returns:
         *         更新后的偏好设置
         */
        post: operations["update_preferences_endpoint_api_update_preferences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-preferences/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Preferences Endpoint
         * @description 获取用户当前的偏好设置
         *
         *     Args:
         *         user_id: 用户ID
         *
         *     Returns:
         *         用户偏好设置，包括：
         *         - user_id: 用户ID
         *         - preferences: 偏好设置字典
         */
        get: operations["get_user_preferences_endpoint_api_user_preferences__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user-profile/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User Profile Endpoint
         * @description Return the three-layer profile for editing/fusion.
         */
        get: operations["get_user_profile_endpoint_api_user_profile__user_id__get"];
        /**
         * Update User Profile Endpoint
         * @description Persist the three-layer profile. The restaurant slice maps onto the legacy
         *     ``dining_habits`` column; other domains and the persona/constraints live in
         *     ``metadata`` — keeping existing restaurant data backward compatible.
         */
        put: operations["update_user_profile_endpoint_api_user_profile__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description 健康检查
         *
         *     Returns:
         *         服务健康状态
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/api-playground/generate-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Api Playground Input */
        post: operations["generate_api_playground_input_internal_debug_api_playground_generate_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/behavior-tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Behavior */
        get: operations["list_behavior_internal_debug_behavior_tests_get"];
        put?: never;
        /** Start Behavior */
        post: operations["start_behavior_internal_debug_behavior_tests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/behavior-tests/track": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Track */
        post: operations["start_track_internal_debug_behavior_tests_track_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/behavior-tests/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Behavior */
        get: operations["get_behavior_internal_debug_behavior_tests__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/behavior-tests/{run_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Endpoint */
        post: operations["explain_endpoint_internal_debug_behavior_tests__run_id__explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_internal_debug_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/unit-tests/generate-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Unit Input */
        post: operations["generate_unit_input_internal_debug_unit_tests_generate_input_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/unit-tests/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Unit */
        post: operations["run_unit_internal_debug_unit_tests_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/internal/debug/unit-tests/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Units */
        get: operations["list_units_internal_debug_unit_tests_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AddMessageRequest
         * @description 添加消息请求
         */
        AddMessageRequest: {
            /** Content */
            content: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
            /** Role */
            role: string;
        };
        /** AdminUserAPI */
        AdminUserAPI: {
            /** Created At */
            created_at?: string | null;
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Last Seen At */
            last_seen_at?: string | null;
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** AdminUserCreateAPI */
        AdminUserCreateAPI: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /**
             * Role
             * @default user
             */
            role: string;
            /**
             * Status
             * @default active
             */
            status: string;
        };
        /** AdminUserListAPI */
        AdminUserListAPI: {
            /** Items */
            items: components["schemas"]["AdminUserAPI"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** AdminUserUpdateAPI */
        AdminUserUpdateAPI: {
            /** Display Name */
            display_name?: string | null;
            /** Expected Updated At */
            expected_updated_at?: string | null;
            /** Role */
            role?: string | null;
            /** Status */
            status?: string | null;
        };
        /** ApiInfoResponseAPI */
        ApiInfoResponseAPI: {
            /** Message */
            message: string;
            /** Version */
            version: string;
        };
        /** ApiPlaygroundInputGenerateRequest */
        ApiPlaygroundInputGenerateRequest: {
            /** Method */
            method?: string | null;
            /**
             * Mode
             * @default schema
             */
            mode: string;
            /** Path */
            path?: string | null;
            /** Schema */
            schema: {
                [key: string]: unknown;
            };
            /** Summary */
            summary?: string | null;
        };
        /** AuthResponseAPI */
        AuthResponseAPI: {
            session: components["schemas"]["AuthSessionAPI"];
            user: components["schemas"]["AuthUserAPI"];
        };
        /** AuthSessionAPI */
        AuthSessionAPI: {
            /** Anonymous Device Id */
            anonymous_device_id?: string | null;
            /** Expires At */
            expires_at: string;
            /** Id */
            id: string;
            /** Status */
            status: string;
            /** User Id */
            user_id: string;
        };
        /** AuthUserAPI */
        AuthUserAPI: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Role */
            role: string;
            /** Status */
            status: string;
        };
        /** BehaviorTestCreateRequest */
        BehaviorTestCreateRequest: {
            /**
             * Auto Confirm
             * @default true
             */
            auto_confirm: boolean;
            /**
             * Confirm Message
             * @default Yes, that's correct
             */
            confirm_message: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Max Wait Seconds
             * @default 90
             */
            max_wait_seconds: number;
            /**
             * Poll Interval Ms
             * @default 500
             */
            poll_interval_ms: number;
            /** Query */
            query: string;
            /**
             * Use Online Agent
             * @default false
             */
            use_online_agent: boolean;
        };
        /** BehaviorTrackRequest */
        BehaviorTrackRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /**
             * Max Wait Seconds
             * @default 90
             */
            max_wait_seconds: number;
            /**
             * Poll Interval Ms
             * @default 500
             */
            poll_interval_ms: number;
            /** Task Id */
            task_id: string;
            /** User Id */
            user_id?: string | null;
        };
        /**
         * BranchData
         * @description Conversation branch metadata.
         */
        BranchData: {
            /** Created At */
            created_at: string;
            /** Fork From Message Id */
            fork_from_message_id?: string | null;
            /** Head Message Id */
            head_message_id?: string | null;
            /** Id */
            id: string;
            /** Parent Branch Id */
            parent_branch_id?: string | null;
            /** Root Message Id */
            root_message_id?: string | null;
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** BudgetRangeInputAPI */
        BudgetRangeInputAPI: {
            /**
             * Currency
             * @default SGD
             */
            currency: string;
            /**
             * Max
             * @default 60
             */
            max: number | null;
            /**
             * Min
             * @default 20
             */
            min: number | null;
            /**
             * Per
             * @default person
             */
            per: string;
        };
        /** ConfirmationQuickActionAPI */
        ConfirmationQuickActionAPI: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Message */
            message?: string | null;
            /** Preference Patch */
            preference_patch?: {
                [key: string]: unknown;
            };
            /** Value */
            value: string;
        };
        /** ConfirmationRequestAPI */
        ConfirmationRequestAPI: {
            /** Message */
            message: string;
            /**
             * Needs Confirmation
             * @default true
             */
            needs_confirmation: boolean;
            /** Preference Form */
            preference_form?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
            /** Quick Actions */
            quick_actions?: components["schemas"]["ConfirmationQuickActionAPI"][] | null;
        };
        /**
         * ConversationData
         * @description 完整对话数据
         */
        ConversationData: {
            /**
             * Active Branch Id
             * @default branch-main
             */
            active_branch_id: string | null;
            /** Branch Selection State */
            branch_selection_state?: {
                [key: string]: string;
            };
            /** Branches */
            branches?: {
                [key: string]: components["schemas"]["BranchData"];
            };
            /** Id */
            id: string;
            /** Last Message */
            last_message: string;
            /** Messages */
            messages: components["schemas"]["MessageData"][];
            /** Model */
            model: string;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
            /** Timestamp */
            timestamp: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
            /** User Id */
            user_id: string;
        };
        /**
         * ConversationSummary
         * @description 对话摘要（用于列表）
         */
        ConversationSummary: {
            /** Id */
            id: string;
            /** Last Message */
            last_message: string;
            /** Message Count */
            message_count: number;
            /** Model */
            model: string;
            /** Timestamp */
            timestamp: string;
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * CreateConversationRequest
         * @description 创建对话请求
         */
        CreateConversationRequest: {
            /**
             * Model
             * @default Auto
             */
            model: string;
            /** Title */
            title?: string | null;
        };
        /** DomainPreferenceFormAPI */
        DomainPreferenceFormAPI: {
            /**
             * Complete
             * @default true
             */
            complete: boolean;
            /** Domain */
            domain: string;
            /** Fields */
            fields?: components["schemas"]["PreferenceFieldAPI"][];
            /** Missing Required */
            missing_required?: string[];
        };
        /** ExplainRequest */
        ExplainRequest: {
            /**
             * Mode
             * @default nl_explain
             */
            mode: string;
        };
        /** FeedbackCreateAPI */
        FeedbackCreateAPI: {
            /** Branch Id */
            branch_id?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Message Id */
            message_id?: string | null;
            /** Reason */
            reason?: ("too_far" | "not_related" | "inaccurate" | "lack_options" | "others") | null;
            /** Result Id */
            result_id?: string | null;
            /**
             * Sentiment
             * @enum {string}
             */
            sentiment: "up" | "down";
            /** Task Id */
            task_id?: string | null;
        };
        /** FeedbackOptionAPI */
        FeedbackOptionAPI: {
            /** Code */
            code: string;
            /** Label */
            label: string;
        };
        /** FeedbackOptionsAPI */
        FeedbackOptionsAPI: {
            /** Reasons */
            reasons: components["schemas"]["FeedbackOptionAPI"][];
        };
        /** FrontendConfigResponseAPI */
        FrontendConfigResponseAPI: {
            /** Googlemapsapikey */
            googleMapsApiKey: string;
        };
        /** GenericSuccessResponseAPI */
        GenericSuccessResponseAPI: {
            /** Message */
            message: string;
            /** Success */
            success: boolean;
        };
        /** GuestLoginRequestAPI */
        GuestLoginRequestAPI: {
            /** Device Id */
            device_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponseAPI */
        HealthResponseAPI: {
            /** Status */
            status: string;
            /** Timestamp */
            timestamp: string;
        };
        /** LoginRequestAPI */
        LoginRequestAPI: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * MessageData
         * @description 消息数据
         */
        MessageData: {
            /** Branch Id */
            branch_id?: string | null;
            /** Content */
            content: string;
            /** Fork From Message Id */
            fork_from_message_id?: string | null;
            /** Id */
            id?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
            /** Parent Message Id */
            parent_message_id?: string | null;
            /** Revision Of Message Id */
            revision_of_message_id?: string | null;
            /** Role */
            role: string;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** PreferenceFieldAPI */
        PreferenceFieldAPI: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Options */
            options?: string[];
            /**
             * Placeholder
             * @default
             */
            placeholder: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Type */
            type: string;
            /** Value */
            value?: unknown | null;
        };
        /** PreferencesResponseAPI */
        PreferencesResponseAPI: {
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
        };
        /** ProcessMessageAPI */
        ProcessMessageAPI: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /** ProcessRequestAPI */
        ProcessRequestAPI: {
            /** Branch Id */
            branch_id?: string | null;
            /** Conversation History */
            conversation_history?: components["schemas"]["ProcessMessageAPI"][] | null;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Domain Lock */
            domain_lock?: string | null;
            /** Hitl State */
            hitl_state?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
            /** Parent Message Id */
            parent_message_id?: string | null;
            /** Query */
            query: string;
            /** Replay From Message Id */
            replay_from_message_id?: string | null;
            /** Source Message Id */
            source_message_id?: string | null;
            /** Time Travel Mode */
            time_travel_mode?: string | null;
            /**
             * Use Online Agent
             * @default false
             */
            use_online_agent: boolean;
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /** RecommendationItemAPI */
        RecommendationItemAPI: {
            /** Description */
            description?: string | null;
            /** Domain */
            domain: string;
            /** Id */
            id: string;
            /** Image Url */
            image_url?: string | null;
            /** Rating */
            rating?: number | null;
            /** Reviews Count */
            reviews_count?: number | null;
            /** Source */
            source?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Tags */
            tags?: string[];
            /** Title */
            title: string;
            /** Url */
            url?: string | null;
            /** Why */
            why?: string | null;
        };
        /** RecommendationResponseAPI */
        RecommendationResponseAPI: {
            confirmation_request?: components["schemas"]["ConfirmationRequestAPI"] | null;
            /** Domain */
            domain?: string | null;
            /** Hitl State */
            hitl_state?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
            /** Intent */
            intent?: string | null;
            /** Items */
            items?: components["schemas"]["RecommendationItemAPI"][];
            /** Llm Reply */
            llm_reply?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
            /** Restaurants */
            restaurants: components["schemas"]["RestaurantAPI"][];
            /** Result Id */
            result_id?: string | null;
            /** Task Id */
            task_id?: string | null;
            /** Thinking Steps */
            thinking_steps?: components["schemas"]["ThinkingStepAPI"][] | null;
            /** Time Travel */
            time_travel?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
        };
        /** RegisterRequestAPI */
        RegisterRequestAPI: {
            /** Display Name */
            display_name?: string | null;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** RestaurantAPI */
        RestaurantAPI: {
            /** Address */
            address?: string | null;
            /** Area */
            area?: string | null;
            /** Cuisine */
            cuisine?: string | null;
            /** Distance Or Walk Time */
            distance_or_walk_time?: string | null;
            /** Flavor Match */
            flavor_match?: string[] | null;
            /** Gps Coordinates */
            gps_coordinates?: {
                [key: string]: number;
            } | null;
            /** Highlights */
            highlights?: string[] | null;
            /** Id */
            id: string;
            /** Location */
            location?: string | null;
            /** Name */
            name: string;
            /** Open Hours Note */
            open_hours_note?: string | null;
            /** Phone */
            phone?: string | null;
            /** Price */
            price?: string | null;
            /** Price Per Person Sgd */
            price_per_person_sgd?: string | null;
            /** Purpose Match */
            purpose_match?: string[] | null;
            /** Rating */
            rating?: number | null;
            /** Reason */
            reason?: string | null;
            /** Reference */
            reference?: string | null;
            /** Reviews Count */
            reviews_count?: number | null;
            /** Sources */
            sources?: {
                [key: string]: string;
            } | null;
            /** Type */
            type?: string | null;
            /** Why */
            why?: string | null;
        };
        /** SetActiveBranchRequest */
        SetActiveBranchRequest: {
            /** Branch Id */
            branch_id: string;
            /** Source Message Id */
            source_message_id?: string | null;
        };
        /** TaskStatusAPI */
        TaskStatusAPI: {
            /** Error */
            error?: string | null;
            /** Message */
            message: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | {
                [key: string]: unknown;
            } | null;
            /** Progress */
            progress: number;
            result?: components["schemas"]["RecommendationResponseAPI"] | null;
            /** Status */
            status: string;
            /** Task Id */
            task_id: string;
        };
        /** ThinkingStepAPI */
        ThinkingStepAPI: {
            /** Description */
            description: string;
            /** Details */
            details?: string | null;
            /** Status */
            status: string;
            /** Step */
            step: string;
        };
        /** UnitInputGenerateRequest */
        UnitInputGenerateRequest: {
            /**
             * Mode
             * @default schema
             */
            mode: string;
            /** Unit Name */
            unit_name: string;
        };
        /** UnitRunRequest */
        UnitRunRequest: {
            /** Input Data */
            input_data?: {
                [key: string]: unknown;
            } | null;
            /**
             * Input Mode
             * @default manual
             */
            input_mode: string;
            /** Unit Name */
            unit_name: string;
            /**
             * Use Llm Generation
             * @default false
             */
            use_llm_generation: boolean;
        };
        /**
         * UpdateConversationRequest
         * @description 更新对话请求
         */
        UpdateConversationRequest: {
            /** Model */
            model?: string | null;
            /** Title */
            title?: string | null;
        };
        /** UpdatePreferencesRequestAPI */
        UpdatePreferencesRequestAPI: {
            /**
             * @default {
             *       "currency": "SGD",
             *       "max": 60,
             *       "min": 20,
             *       "per": "person"
             *     }
             */
            budgetRange: components["schemas"]["BudgetRangeInputAPI"];
            /**
             * Diningpurpose
             * @default any
             */
            diningPurpose: string;
            /**
             * Flavorprofiles
             * @default [
             *       "any"
             *     ]
             */
            flavorProfiles: string[];
            /**
             * Location
             * @default any
             */
            location: string;
            /**
             * Restauranttypes
             * @default [
             *       "any"
             *     ]
             */
            restaurantTypes: string[];
            /**
             * User Id
             * @default default
             */
            user_id: string;
        };
        /** UpdatePreferencesResponseAPI */
        UpdatePreferencesResponseAPI: {
            /** Message */
            message: string;
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
        };
        /** UserPreferencesResponseAPI */
        UserPreferencesResponseAPI: {
            /** Preferences */
            preferences?: {
                [key: string]: unknown;
            };
            /** User Id */
            user_id: string;
        };
        /**
         * UserProfileAPI
         * @description Three-layer user profile: generic core (demographics + cross-domain
         *     constraints), an NL taste persona, and per-domain structured slices.
         */
        UserProfileAPI: {
            /** Constraints */
            constraints?: {
                [key: string]: unknown;
            };
            /** Demographics */
            demographics?: {
                [key: string]: unknown;
            };
            /** Domains */
            domains?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Taste Persona
             * @default
             */
            taste_persona: string;
            /** User Id */
            user_id: string;
        };
        /** UserProfileUpdateAPI */
        UserProfileUpdateAPI: {
            /** Constraints */
            constraints?: {
                [key: string]: unknown;
            };
            /** Demographics */
            demographics?: {
                [key: string]: unknown;
            };
            /** Domains */
            domains?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            /**
             * Taste Persona
             * @default
             */
            taste_persona: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_root_api_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiInfoResponseAPI"];
                };
            };
        };
    };
    session_info_api_admin_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_stats_api_admin_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_users_api_admin_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
                role?: string | null;
                status?: string | null;
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserCreateAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_api_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdateAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guest_login_api_auth_guest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuestLoginRequestAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericSuccessResponseAPI"];
                };
            };
        };
    };
    register_api_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponseAPI"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrontendConfigResponseAPI"];
                };
            };
        };
    };
    get_all_conversations_api_conversations__user_id__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_conversations__user_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__user_id___conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_conversations__user_id___conversation_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateConversationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__user_id___conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericSuccessResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_active_branch_api_conversations__user_id___conversation_id__active_branch_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetActiveBranchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_message_api_conversations__user_id___conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericSuccessResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_preferences_api_conversations__user_id___conversation_id__preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_preferences_api_conversations__user_id___conversation_id__preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_llm_connection_api_debug_llm_connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_domain_preference_form_api_domains__domain__preference_form_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainPreferenceFormAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreateAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_options_api_feedback_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedbackOptionsAPI"];
                };
            };
        };
    };
    process_user_request_api_process_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProcessRequestAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_status__task_id__get: {
        parameters: {
            query?: {
                user_id?: string | null;
                conversation_id?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStatusAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_task_status_api_status__task_id__stream_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                conversation_id?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_result_api_tasks__task_id__result_get: {
        parameters: {
            query?: {
                user_id?: string | null;
                conversation_id?: string | null;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_preferences_endpoint_api_update_preferences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequestAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdatePreferencesResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_preferences_endpoint_api_user_preferences__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferencesResponseAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_profile_endpoint_api_user_profile__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_profile_endpoint_api_user_profile__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProfileUpdateAPI"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileAPI"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseAPI"];
                };
            };
        };
    };
    generate_api_playground_input_internal_debug_api_playground_generate_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiPlaygroundInputGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_behavior_internal_debug_behavior_tests_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    start_behavior_internal_debug_behavior_tests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BehaviorTestCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_track_internal_debug_behavior_tests_track_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BehaviorTrackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_behavior_internal_debug_behavior_tests__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_endpoint_internal_debug_behavior_tests__run_id__explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_internal_debug_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generate_unit_input_internal_debug_unit_tests_generate_input_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitInputGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_unit_internal_debug_unit_tests_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnitRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_units_internal_debug_unit_tests_units_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
