[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "metarec"
version = "0.0.001"
description = 'backend for MetaRec'

dependencies = [
    # from requirements.txt, with versions removed
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-multipart",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "python-dotenv",
    "aiofiles",
    "openai",
    "httpx",
    "requests",
    "cryptography",

    # additional
    "fastmcp",
    "pillow",
    "langgraph",
    "langchain-core",
    "langchain-openai",
    "hishel[async]",
    "jinja2",
]

[tool.hatch.build.targets.wheel]
packages = [ "Metarec-backend/src/metarec" ]

[tool.hatch.build.targets.wheel.force-include]
"Metarec-ui/dist" = "Metarec-backend/src/metarec/frontend-dist"

[tool.hatch.build.targets.sdist.force-include]
# for each key in target.wheel
# not doing this may cause issues with sdist target
"Metarec-ui/dist" = "Metarec-ui/dist"
