[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "metarec"
version = "0.0.001"
description = 'backend for MetaRec'

dependencies = [
    # from requirements.txt, with versions removed
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-multipart",
    "python-jose[cryptography]",
    "passlib[bcrypt]",
    "python-dotenv",
    "aiofiles",
    "openai",
    "httpx",
    "requests",
    "cryptography",

    # additional
    "fastmcp",
    "pillow",
    "langgraph",
    "langchain-core",
    "langchain-openai",
    "hishel[async]",
    "jinja2",
    
    # storage
    "pickledb"
]

[tool.hatch.build.targets.wheel]
packages = [ "Metarec-backend/src/metarec" ]


[tool.hatch.build.targets.dist.hooks.custom]
path = 'build_hook.py'

[tool.hatch.build.targets.wheel.hooks.custom]
path = 'build_hook.py'
dependencies = [
    #'langchain-core',
    #'langgraph',
    #'fastmcp',
    #'openai',
]


