"""Regenerate scripts/probe_solver.py from the real solver.

The probe is a mechanical transform of langgraph_metarec/itinerary_solver.py:
a PROBE recording dict, instrumented beam-trim lines, and final-ranking
recorders. Hand-maintaining the fork is how it shipped stale once (it missed
the post-loop finals harvest, biasing every multi-day sweep), so the transform
lives here instead: run `python scripts/sync_probe_solver.py` after touching
the solver. tests/test_probe_solver_sync.py fails while the checked-in probe
lags this generator's output.
"""
from __future__ import annotations

from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parents[1]
SOLVER_PATH = BACKEND_ROOT / "langgraph_metarec" / "itinerary_solver.py"
PROBE_PATH = BACKEND_ROOT / "scripts" / "probe_solver.py"

_DOCSTRING = '''"""Instrumented copy of langgraph_metarec/itinerary_solver.py for objective sweeps.

Calibration harness only -- never import from the app. It records beam-trim
sizes, tie depths in the objective key, and final-ranking decisions into the
module-level PROBE dict (see the ROLE_REPEAT_DISCOUNT / TRANSITION_COST_MIN
sweep notes in the real solver). GENERATED by scripts/sync_probe_solver.py --
edit the transform there, never this file; tests/test_probe_solver_sync.py
fails while this file lags the solver. Run from MetaRec-backend/ so the
langgraph_metarec imports resolve.
"""'''

_PROBE_HELPERS = '''

PROBE = {"trim": [], "final": [], "beamtie": []}

def _tie_depth(a, b):
    for i, (x, y) in enumerate(zip(a, b)):
        if x != y:
            return i
    return -1

def _record_final(rows, tag):
    keys = sorted(row[0] for row in rows)
    depth = _tie_depth(keys[0], keys[1]) if len(keys) > 1 else None
    PROBE["final"].append({"tag": tag, "n": len(keys), "decided_at": depth})


'''

_TRIM_TEMPLATE = (
    '            _ranked = sorted(dominant.values(), key={key})\n'
    '            PROBE["trim"].append({{"tag": "{tag}", "generated": len(next_states), '
    '"after_agg": len(dominant), "kept": min(len(dominant), self.beam_width), '
    '"width": self.beam_width}})\n'
    '            if len(_ranked) > 1:\n'
    '                PROBE["beamtie"].append({{"tag": "{tag}", "decided_at": '
    '_tie_depth({key}(_ranked[0]), {key}(_ranked[1]))}})\n'
    '            beam = _ranked[:self.beam_width]'
)


def _replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(
            f"sync_probe_solver: anchor for {label} matched {count} times "
            f"(expected exactly 1); the solver changed shape -- update the transform."
        )
    return text.replace(old, new)


def generate(solver_text: str) -> str:
    text = solver_text.replace("\r\n", "\n")
    text = _replace_once(
        text,
        '"""Deterministic dynamic itinerary solver over the provider-free planning IR."""',
        _DOCSTRING,
        "module docstring",
    )
    text = _replace_once(
        text,
        "\n@dataclass(frozen=True)\nclass _State:",
        _PROBE_HELPERS + "@dataclass(frozen=True)\nclass _State:",
        "PROBE helpers",
    )
    text = _replace_once(
        text,
        "            beam = sorted(dominant.values(), key=state_key)[:self.beam_width]",
        _TRIM_TEMPLATE.format(key="state_key", tag="multi"),
        "multi-day beam trim",
    )
    text = _replace_once(
        text,
        "            beam = sorted(dominant.values(), key=single_day_state_key)[:self.beam_width]",
        _TRIM_TEMPLATE.format(key="single_day_state_key", tag="single"),
        "single-day beam trim",
    )
    text = _replace_once(
        text,
        "        _key, winner, components = min(final_rows, key=lambda row: row[0])",
        '        _record_final(final_rows, "multi")\n'
        "        _key, winner, components = min(final_rows, key=lambda row: row[0])",
        "multi-day final recorder",
    )
    text = _replace_once(
        text,
        "        _, winner, objective_components = min(scored_finals, key=lambda row: row[0])",
        '        _record_final(scored_finals, "single")\n'
        "        _, winner, objective_components = min(scored_finals, key=lambda row: row[0])",
        "single-day final recorder",
    )
    return text


def main() -> None:
    probe = generate(SOLVER_PATH.read_text(encoding="utf-8"))
    PROBE_PATH.write_text(probe, encoding="utf-8", newline="\n")
    print(f"wrote {PROBE_PATH.relative_to(BACKEND_ROOT)} ({len(probe.splitlines())} lines)")


if __name__ == "__main__":
    main()
